const productsData = [
  {
    title: "Food",
    path: "/products/food",
    tagline: "Savor imported and exported delicacies",
    products: [
      {
        id: 1,
        name: "Exotic Fruits",
        image: "https://via.placeholder.com/150",
        price: "$15",
        tagline: "Taste the world in every bite",
      },
      {
        id: 2,
        name: "Gourmet Spices",
        image: "https://via.placeholder.com/150",
        price: "$20",
        tagline: "Elevate your cooking",
      },
      {
        id: 3,
        name: "Organic Vegetables",
        image: "https://via.placeholder.com/150",
        price: "$10",
        tagline: "Fresh from the farm",
      },
      {
        id: 4,
        name: "Premium Dairy Products",
        image: "https://via.placeholder.com/150",
        price: "$12",
        tagline: "Healthy and delicious",
      },
      {
        id: 5,
        name: "Fine Wines",
        image: "https://via.placeholder.com/150",
        price: "$50",
        tagline: "A taste of luxury",
      },
      {
        id: 6,
        name: "Artisanal Bread",
        image: "https://via.placeholder.com/150",
        price: "$8",
        tagline: "Freshly baked every day",
      },
      {
        id: 7,
        name: "Luxury Chocolates",
        image: "https://via.placeholder.com/150",
        price: "$25",
        tagline: "Indulge your sweet tooth",
      },
      {
        id: 8,
        name: "Specialty Tea",
        image: "https://via.placeholder.com/150",
        price: "$18",
        tagline: "Relax with every sip",
      },
      {
        id: 9,
        name: "Imported Coffee",
        image: "https://via.placeholder.com/150",
        price: "$22",
        tagline: "Awaken your senses",
      },
    ],
  },
  {
    title: "Marvel",
    path: "/products/marvel",
    tagline: "Premium Marvel stones and surfaces",
    products: [
      {
        id: 1,
        name: "White Marble",
        image: "https://via.placeholder.com/150",
        price: "$100",
        tagline: "Classic and timeless",
      },
      {
        id: 2,
        name: "Black Granite",
        image: "https://via.placeholder.com/150",
        price: "$120",
        tagline: "Bold and beautiful",
      },
      {
        id: 3,
        name: "Polished Onyx",
        image: "https://via.placeholder.com/150",
        price: "$150",
        tagline: "Elegance redefined",
      },
      {
        id: 4,
        name: "Travertine Tiles",
        image: "https://via.placeholder.com/150",
        price: "$90",
        tagline: "Rustic and warm",
      },
      {
        id: 5,
        name: "Quartz Slabs",
        image: "https://via.placeholder.com/150",
        price: "$110",
        tagline: "Durable and stunning",
      },
      {
        id: 6,
        name: "Limestone Blocks",
        image: "https://via.placeholder.com/150",
        price: "$80",
        tagline: "Natural and versatile",
      },
      {
        id: 7,
        name: "Soapstone Surfaces",
        image: "https://via.placeholder.com/150",
        price: "$95",
        tagline: "Smooth and sophisticated",
      },
      {
        id: 8,
        name: "Sandstone Pavers",
        image: "https://via.placeholder.com/150",
        price: "$75",
        tagline: "Perfect for exteriors",
      },
      {
        id: 9,
        name: "Terrazzo Patterns",
        image: "https://via.placeholder.com/150",
        price: "$130",
        tagline: "Modern and artistic",
      },
    ],
  },
  {
    title: "Metal",
    path: "/products/metal",
    tagline: "High-grade metals for every need",
    products: [
      {
        id: 1,
        name: "Stainless Steel Sheets",
        image: "https://via.placeholder.com/150",
        price: "$200",
        tagline: "Resilient and versatile",
      },
      {
        id: 2,
        name: "Aluminum Coils",
        image: "https://via.placeholder.com/150",
        price: "$180",
        tagline: "Lightweight and durable",
      },
      {
        id: 3,
        name: "Copper Wires",
        image: "https://via.placeholder.com/150",
        price: "$250",
        tagline: "Excellent conductivity",
      },
      {
        id: 4,
        name: "Galvanized Iron",
        image: "https://via.placeholder.com/150",
        price: "$160",
        tagline: "Rust-free assurance",
      },
      {
        id: 5,
        name: "Titanium Rods",
        image: "https://via.placeholder.com/150",
        price: "$300",
        tagline: "Strength and flexibility",
      },
      {
        id: 6,
        name: "Bronze Sculptures",
        image: "https://via.placeholder.com/150",
        price: "$220",
        tagline: "Timeless artistry",
      },
      {
        id: 7,
        name: "Nickel Sheets",
        image: "https://via.placeholder.com/150",
        price: "$240",
        tagline: "Durable and efficient",
      },
      {
        id: 8,
        name: "Zinc Alloys",
        image: "https://via.placeholder.com/150",
        price: "$190",
        tagline: "Perfect for casting",
      },
      {
        id: 9,
        name: "Brass Pipes",
        image: "https://via.placeholder.com/150",
        price: "$210",
        tagline: "Stylish and functional",
      },
    ],
  },
  {
    title: "Toys",
    path: "/products/toys",
    tagline: "High-grade metals for every need",
    products: [
      {
        id: 1,
        name: "Stainless Steel Sheets",
        image: "https://via.placeholder.com/150",
        price: "$200",
        tagline: "Resilient and versatile",
      },
      {
        id: 2,
        name: "Aluminum Coils",
        image: "https://via.placeholder.com/150",
        price: "$180",
        tagline: "Lightweight and durable",
      },
      {
        id: 3,
        name: "Copper Wires",
        image: "https://via.placeholder.com/150",
        price: "$250",
        tagline: "Excellent conductivity",
      },
      {
        id: 4,
        name: "Galvanized Iron",
        image: "https://via.placeholder.com/150",
        price: "$160",
        tagline: "Rust-free assurance",
      },
      {
        id: 5,
        name: "Titanium Rods",
        image: "https://via.placeholder.com/150",
        price: "$300",
        tagline: "Strength and flexibility",
      },
      {
        id: 6,
        name: "Bronze Sculptures",
        image: "https://via.placeholder.com/150",
        price: "$220",
        tagline: "Timeless artistry",
      },
      {
        id: 7,
        name: "Nickel Sheets",
        image: "https://via.placeholder.com/150",
        price: "$240",
        tagline: "Durable and efficient",
      },
      {
        id: 8,
        name: "Zinc Alloys",
        image: "https://via.placeholder.com/150",
        price: "$190",
        tagline: "Perfect for casting",
      },
      {
        id: 9,
        name: "Brass Pipes",
        image: "https://via.placeholder.com/150",
        price: "$210",
        tagline: "Stylish and functional",
      },
    ],
  },
  {
    title: "Ornaments",
    path: "/products/ornaments",
    tagline: "High-grade metals for every need",
    products: [
      {
        id: 1,
        name: "Stainless Steel Sheets",
        image: "https://via.placeholder.com/150",
        price: "$200",
        tagline: "Resilient and versatile",
      },
      {
        id: 2,
        name: "Aluminum Coils",
        image: "https://via.placeholder.com/150",
        price: "$180",
        tagline: "Lightweight and durable",
      },
      {
        id: 3,
        name: "Copper Wires",
        image: "https://via.placeholder.com/150",
        price: "$250",
        tagline: "Excellent conductivity",
      },
      {
        id: 4,
        name: "Galvanized Iron",
        image: "https://via.placeholder.com/150",
        price: "$160",
        tagline: "Rust-free assurance",
      },
      {
        id: 5,
        name: "Titanium Rods",
        image: "https://via.placeholder.com/150",
        price: "$300",
        tagline: "Strength and flexibility",
      },
      {
        id: 6,
        name: "Bronze Sculptures",
        image: "https://via.placeholder.com/150",
        price: "$220",
        tagline: "Timeless artistry",
      },
      {
        id: 7,
        name: "Nickel Sheets",
        image: "https://via.placeholder.com/150",
        price: "$240",
        tagline: "Durable and efficient",
      },
      {
        id: 8,
        name: "Zinc Alloys",
        image: "https://via.placeholder.com/150",
        price: "$190",
        tagline: "Perfect for casting",
      },
      {
        id: 9,
        name: "Brass Pipes",
        image: "https://via.placeholder.com/150",
        price: "$210",
        tagline: "Stylish and functional",
      },
    ],
  },
  {
    title: "Dresses",
    path: "/products/dresses",
    tagline: "High-grade metals for every need",
    products: [
      {
        id: 1,
        name: "Stainless Steel Sheets",
        image: "https://via.placeholder.com/150",
        price: "$200",
        tagline: "Resilient and versatile",
      },
      {
        id: 2,
        name: "Aluminum Coils",
        image: "https://via.placeholder.com/150",
        price: "$180",
        tagline: "Lightweight and durable",
      },
      {
        id: 3,
        name: "Copper Wires",
        image: "https://via.placeholder.com/150",
        price: "$250",
        tagline: "Excellent conductivity",
      },
      {
        id: 4,
        name: "Galvanized Iron",
        image: "https://via.placeholder.com/150",
        price: "$160",
        tagline: "Rust-free assurance",
      },
      {
        id: 5,
        name: "Titanium Rods",
        image: "https://via.placeholder.com/150",
        price: "$300",
        tagline: "Strength and flexibility",
      },
      {
        id: 6,
        name: "Bronze Sculptures",
        image: "https://via.placeholder.com/150",
        price: "$220",
        tagline: "Timeless artistry",
      },
      {
        id: 7,
        name: "Nickel Sheets",
        image: "https://via.placeholder.com/150",
        price: "$240",
        tagline: "Durable and efficient",
      },
      {
        id: 8,
        name: "Zinc Alloys",
        image: "https://via.placeholder.com/150",
        price: "$190",
        tagline: "Perfect for casting",
      },
      {
        id: 9,
        name: "Brass Pipes",
        image: "https://via.placeholder.com/150",
        price: "$210",
        tagline: "Stylish and functional",
      },
    ],
  },
  {
    title: "Artifacts",
    path: "/products/artifacts",
    tagline: "High-grade metals for every need",
    products: [
      {
        id: 1,
        name: "Stainless Steel Sheets",
        image: "https://via.placeholder.com/150",
        price: "$200",
        tagline: "Resilient and versatile",
      },
      {
        id: 2,
        name: "Aluminum Coils",
        image: "https://via.placeholder.com/150",
        price: "$180",
        tagline: "Lightweight and durable",
      },
      {
        id: 3,
        name: "Copper Wires",
        image: "https://via.placeholder.com/150",
        price: "$250",
        tagline: "Excellent conductivity",
      },
      {
        id: 4,
        name: "Galvanized Iron",
        image: "https://via.placeholder.com/150",
        price: "$160",
        tagline: "Rust-free assurance",
      },
      {
        id: 5,
        name: "Titanium Rods",
        image: "https://via.placeholder.com/150",
        price: "$300",
        tagline: "Strength and flexibility",
      },
      {
        id: 6,
        name: "Bronze Sculptures",
        image: "https://via.placeholder.com/150",
        price: "$220",
        tagline: "Timeless artistry",
      },
      {
        id: 7,
        name: "Nickel Sheets",
        image: "https://via.placeholder.com/150",
        price: "$240",
        tagline: "Durable and efficient",
      },
      {
        id: 8,
        name: "Zinc Alloys",
        image: "https://via.placeholder.com/150",
        price: "$190",
        tagline: "Perfect for casting",
      },
      {
        id: 9,
        name: "Brass Pipes",
        image: "https://via.placeholder.com/150",
        price: "$210",
        tagline: "Stylish and functional",
      },
    ],
  },
]

export default productsData